# Generated by Django 5.2.8 on 2025-12-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='perfil_default.png', upload_to='fotos_perfil'),
        ),
    ]
